
source("rcode/common/indexing.R")
source("rcode/common/io.R")
source("rcode/common/linear.R")
source("rcode/common/nextPC.R")
source("rcode/common/decode.R")
source("rcode/common/smacof.R")
source("rcode/properties.R")
source("rcode/pictures.R")
source("rcode/classical.R")
source("rcode/accelerate.R")
source("rcode/full.R")
source("rcode/unfolding.R")
source("rcode/constrained.R")
source("rcode/nominal.R")
source("rcode/sstress.R")
source("rcode/inverse.R")
source("rcode/global.R")
source("rcode/smacofEps.R")
source("rcode/mathadd.R")
source("rcode/expandOneDim.R")
source("rcode/equalDelta.R")

dyn.load("lib/deboor.so")
dyn.load("lib/nextPC.so")
dyn.load("lib/cleanup.so")
dyn.load("lib/jeffrey.so")
dyn.load("lib/jacobi.so")
dyn.load("lib/jbkTies.so")
dyn.load("lib/matrix.so")
#dyn.load("lib/mySort.so")

suppressPackageStartupMessages(library (knitr, quietly = TRUE))
suppressPackageStartupMessages(library (kableExtra, quietly = TRUE))
suppressPackageStartupMessages(library (microbenchmark, quietly = TRUE))
suppressPackageStartupMessages(library (polynom, quietly = TRUE))
suppressPackageStartupMessages(library (hasseDiagram, quietly = TRUE))
suppressPackageStartupMessages(library (rlist, quietly = TRUE))
suppressPackageStartupMessages(library (MASS, quietly = TRUE))
suppressPackageStartupMessages(library (lsei, quietly = TRUE))
suppressPackageStartupMessages(library (rcdd, quietly = TRUE))
suppressPackageStartupMessages(library (numDeriv, quietly = TRUE))
#suppressPackageStartupMessages(library (vertexenum, quietly = TRUE))
suppressPackageStartupMessages(library (lpSolve, quietly = TRUE))
suppressPackageStartupMessages(library (quadprog, quietly = TRUE))
suppressPackageStartupMessages(library (combinat, quietly = TRUE))

source("data/dsmall.R")
source("data/ekman.R")
source("data/gruijter.R")
source("data/veggies.R")
source("data/births.R")

