<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Interval MDS – Least Squares Euclidean Multidimensional Scaling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./polynomial.html" rel="next">
<link href="./nonmetric.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
</head><body class="nav-sidebar floating">.greybox {
  padding: 1em;
  background: white;
  color: black;
  border: 2px solid orange;
  border-radius: 10px;
}
.center {
  text-align: center;
}

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>





<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./interval.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Interval MDS</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Least Squares Euclidean Multidimensional Scaling</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Note</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notation and Reserved Symbols</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./properties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Properties of Stress</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spaces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Stress Spaces</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Classical Multidimensional Scaling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./minimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Minimization of Basic Stress</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./acceleration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Acceleration of Convergence</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonmetric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Nonmetric MDS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interval.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Interval MDS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./polynomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Polynomial MDS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ordinal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Ordinal MDS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./splinical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Splinical MDS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidimensional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Unidimensional Scaling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./full.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Full-dimensional Scaling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unfolding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Unfolding</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./constrained.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Constrained Multidimensional Scaling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./individual.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Individual Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./asymmetry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Asymmetry in MDS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nominal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Nominal MDS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonordinal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Nonmonotonic MDS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nonpairs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Compound Objects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sstress.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">sstress</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rstress.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">fstress and rstress</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./altls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Alternative Least Squares Loss</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Inverse Multidimensional Scaling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Stability of MDS Solutions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./global.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">In Search of Global Minima</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./software.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Software</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./backmatter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">(APPENDIX) Appendices</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#intadditive" id="toc-intadditive" class="nav-link active" data-scroll-target="#intadditive"><span class="header-section-number">8.1</span> The Additive Constant</a>
  <ul class="collapse">
  <li><a href="#early" id="toc-early" class="nav-link" data-scroll-target="#early"><span class="header-section-number">8.1.1</span> Early</a></li>
  <li><a href="#cooper" id="toc-cooper" class="nav-link" data-scroll-target="#cooper"><span class="header-section-number">8.1.2</span> Cooper</a></li>
  </ul></li>
  <li><a href="#exactad" id="toc-exactad" class="nav-link" data-scroll-target="#exactad"><span class="header-section-number">8.2</span> Algebra</a>
  <ul class="collapse">
  <li><a href="#existence" id="toc-existence" class="nav-link" data-scroll-target="#existence"><span class="header-section-number">8.2.1</span> Existence</a></li>
  <li><a href="#solution" id="toc-solution" class="nav-link" data-scroll-target="#solution"><span class="header-section-number">8.2.2</span> Solution</a></li>
  <li><a href="#examples" id="toc-examples" class="nav-link" data-scroll-target="#examples"><span class="header-section-number">8.2.3</span> Examples</a></li>
  <li><a href="#variation" id="toc-variation" class="nav-link" data-scroll-target="#variation"><span class="header-section-number">8.2.4</span> A Variation</a></li>
  </ul></li>
  <li><a href="#interval-smacof" id="toc-interval-smacof" class="nav-link" data-scroll-target="#interval-smacof"><span class="header-section-number">8.3</span> Interval smacof</a>
  <ul class="collapse">
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example"><span class="header-section-number">8.3.1</span> Example</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="intinterval" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Interval MDS</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>intro: additive vs interval basic vs ratio</p>
<section id="intadditive" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="intadditive"><span class="header-section-number">8.1</span> The Additive Constant</h2>
<section id="early" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="early"><span class="header-section-number">8.1.1</span> Early</h3>
<p>In the early history of MDS dissimilarities were computed from comparative judgments in the Thurstonian tradition.</p>
<p>triads paired comparisons etc positive orthant</p>
<p>These early techniques only gave numbers on an interval scale, i.e.&nbsp;dissimilarities known only up to a linear transformation. In order to get positive dissimilarities a rational origin needed to be found in some way. This is the <em>additive constant problem</em>. It can be seen as the first example of nonmetric MDS, in which we have only partially known dissimilarities (up to an additive constant).</p>
<p><span class="math display">\[\begin{align}
\begin{split}
(\delta_{ij}+\alpha)&amp;\approx d_{ij}(X),\\
\delta_{ij}&amp;\approx d_{ij}(X)+\alpha.
\end{split}
(\#eq:twoadd)
\end{align}\]</span></p>
<p>The additive constant techniques were more important in the fifties and sixties than they are these days, because they have largely been replaced by iterative nonmetric MDS techniques.</p>
<p>An early algorithm to fit the additive constant based on Schoenberg’s theorem was given by <span class="citation" data-cites="messick_abelson_56">Messick and Abelson (<a href="references.html#ref-messick_abelson_56" role="doc-biblioref">1956</a>)</span>. Ii was Torgerson based, i.e.&nbsp;it used the eigenvalues of <span class="math inline">\(\tau(\Delta^{(2)})\)</span>. It was a somewhat hopeful iterative technique, without a convergence proof, designed to make the sum of the <span class="math inline">\(n-p\)</span> smallest eigenvalues equal to zero. This is of course only a necessary condition for best approximation, not a sufficient one.</p>
<p>In addition, the Messick-Abelson algorithm sometimes yielded solutionsin which the Torgerson transform of the squared dissimilarities had negative eigenvalues, which could even be quite large. That is also somewhat of a problem.</p>
</section>
<section id="cooper" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="cooper"><span class="header-section-number">8.1.2</span> Cooper</h3>
<p>Consequently <span class="citation" data-cites="cooper_72">Cooper (<a href="references.html#ref-cooper_72" role="doc-biblioref">1972</a>)</span> proposed an alternative additive constant algorithm, taking his clue from the work of Kruskal.</p>
<p>The solution was to redefine stress as a function of both the configuration and the additive constant. Thus</p>
<p><span class="math display">\[\begin{equation}
\sigma(X,\alpha):=\mathop{\sum\sum}_{1\leq j&lt;i\leq n}w_{ij}(\delta_{ij}+\alpha-d_{ij}(X))^2,
(\#eq:nmcooper1)
\end{equation}\]</span></p>
<p>and we minimize this stress over both <span class="math inline">\(X\)</span> and <span class="math inline">\(\alpha\)</span>.</p>
<p>Double phase (ALS)</p>
<p><span class="math inline">\(\delta_{ij}+\alpha\geq 0\)</span></p>
<p>Single Phase (Cooper)</p>
<p><span class="math display">\[\begin{equation}
\sigma(X):=\min_\alpha\mathop{\sum\sum}_{1\leq j&lt;i\leq n}w_{ij}(\delta_{ij}+\alpha-d_{ij}(X))^2,
(\#eq:nmcooper2)
\end{equation}\]</span></p>
</section>
</section>
<section id="exactad" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="exactad"><span class="header-section-number">8.2</span> Algebra</h2>
<p>The additive constant problem is to find <span class="math inline">\(X\in\mathbb{R}^{n\times p}\)</span> and <span class="math inline">\(\alpha\)</span> such that <span class="math inline">\(\Delta+\alpha(E-I)\approx D(X)\)</span>. In this section we look for all <span class="math inline">\(\alpha\)</span> such that <span class="math inline">\(\Delta+\alpha(E-I)\)</span> is Euclidean, i.e. such that there is a configuration <span class="math inline">\(X\)</span> with <span class="math inline">\(\Delta+\alpha(E-I)=D(X)\)</span>. This is a one-parameter generalization of Schoenberg’s theorem.</p>
<p>It makes sense to require <span class="math inline">\(\alpha\geq 0\)</span>, because a negative <span class="math inline">\(\alpha\)</span> would more appropriately be called a subtractive constant. Also, we may want to make sure that the off-diagonal elements of <span class="math inline">\(\Delta+\alpha(E-I)\)</span> are non-negative, i.e.&nbsp;that <span class="math inline">\(\alpha\geq-\delta_{ij}\)</span> for all <span class="math inline">\(i&gt;j\)</span>. Note that if we allow a negative <span class="math inline">\(\alpha\)</span> then if all off-diagonal <span class="math inline">\(\delta_{ij}\)</span> are equal, say to <span class="math inline">\(\delta&gt;0\)</span>, we have the trivial solution <span class="math inline">\(\alpha=-\delta\)</span> and <span class="math inline">\(X=0\)</span>.</p>
<section id="existence" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="existence"><span class="header-section-number">8.2.1</span> Existence</h3>
<p>We start with a simple construction.</p>
<div class="cell">
<pre class="theorem cell-code"><code>For all $\Delta$ there is an $\alpha_0\geq 0$ such that for all $\alpha\geq\alpha_0$ we have $\Delta+\alpha(E-I))$ Euclidean of dimension $r\leq n-1$.</code></pre>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>We have, using <span class="math inline">\(\Delta\times(E-I)=\Delta\)</span> and <span class="math inline">\((E-I)\times(E-I)=E-I\)</span>,</p>
<p><span class="math display">\[\begin{equation}
  \tau((\Delta+\alpha(E-I))\times(\Delta+\alpha(E-I)))=
  \tau(\Delta\times\Delta)+2\alpha\tau(\Delta)+\frac12\alpha^2J.
(\#eq:tau1)
\end{equation}\]</span></p>
<p>Thus each off-diagonal element is a concave quadratic in <span class="math inline">\(\alpha\)</span>, which is negative for <span class="math inline">\(\alpha\)</span> big enough. Choose <span class="math inline">\(\alpha_0\geq 0\)</span> to make all off-diagonal elements negative (and all dissimilarities non-negative). A doubly-centered matrix with all off-diagonal elements negative is positive semi-definite of rank <span class="math inline">\(n-1\)</span> (<span class="citation" data-cites="taussky_49">Taussky (<a href="references.html#ref-taussky_49" role="doc-biblioref">1949</a>)</span>).</p>
</div>
<p>Note that by the same argument we can also find a negative <span class="math inline">\(\alpha_0\)</span> that makes all off-diagonal elements negative and thus <span class="math inline">\(\Delta+\alpha(E-I))\)</span> is again Euclidean of dimension <span class="math inline">\(r\leq n-1\)</span>. But this <span class="math inline">\(\alpha_0\)</span> will usually result in negative dissimilarities.</p>
<p>Theorem @ref(thm:nmn1) can be sharpened for non-Euclidean <span class="math inline">\(\Delta\)</span>. Define the following function of <span class="math inline">\(\alpha\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\lambda_\star(\alpha):=\min_{x'x=1, x'e=0}x'\{\tau(\Delta\times\Delta)+2\alpha\tau(\Delta)+\frac12\alpha^2J\}x.
(\#eq:lambdas)
\end{equation}\]</span></p>
<p>This is the smallest non-trivial eigenvalue of the Torgerson transform in @ref(eq:tau1). The matrix <span class="math inline">\(\Delta+\alpha(E-I)\)</span> is Euclidean if and only if <span class="math inline">\(\lambda_\star(\alpha)\geq 0\)</span>. Note that <span class="math inline">\(\lambda_\star\)</span> is continuous, by a simple special case of the Maximum Theorem (<span class="citation" data-cites="berge_63">Berge (<a href="references.html#ref-berge_63" role="doc-biblioref">1963</a>)</span>, Chapter VI, section 3), and coercive, i.e.&nbsp;<span class="math inline">\(\lambda_\star(\alpha)\rightarrow +\infty\)</span> if <span class="math inline">\(|\alpha|\rightarrow +\infty\)</span>.</p>
<div class="cell">
<pre class="theorem cell-code"><code>For all non-Euclidean $\Delta$ there is an $\alpha_1&gt;0$ such that for all $\alpha\geq\alpha_1$ we have that $\Delta+\alpha(E-I))$ Euclidean of dimension $r\leq n-2$.</code></pre>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Because <span class="math inline">\(\Delta\)</span> is non-Euclidean we have <span class="math inline">\(\lambda_\star(0)&lt;0\)</span>. By the construction in theorem @ref(thm:nmn1) there is an <span class="math inline">\(\alpha_0\)</span> such that <span class="math inline">\(\lambda_\star(\alpha)&gt;0\)</span> for all <span class="math inline">\(\alpha&gt;\alpha_0\)</span>. By the Maximum Theorem the function <span class="math inline">\(\lambda_\star\)</span> is continuous, and thus, by Bolzano’s theorem, there is an <span class="math inline">\(\alpha_1\)</span> between <span class="math inline">\(0\)</span> and <span class="math inline">\(\alpha_0\)</span> such that <span class="math inline">\(\lambda_\star(\alpha_1)=0\)</span>. If there is more than one zero between <span class="math inline">\(0\)</span> and <span class="math inline">\(\alpha_0\)</span> we take the largest one as <span class="math inline">\(\alpha_1\)</span>.</p>
</div>
<p>The problem with extending theorem @ref(thm:nmn2) to Euclidean <span class="math inline">\(\Delta\)</span> is that the equation <span class="math inline">\(\lambda_\star(\alpha)=0\)</span> may have only negative roots, or, even more seriously, no roots at all. This may not be too important from the practical point of view, because observed dissimilarities will usually not be exactly Euclidean. Nevertheless I feel compelled to address it.</p>
<div class="cell">
<pre class="theorem cell-code"><code>If $\Delta$ is Euclidean then $\lambda_\star(\alpha)$ is non-negative and non-decreasing on $[0,+\infty)$.</code></pre>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>If <span class="math inline">\(\Delta\)</span> is Euclidean, then <span class="math inline">\(\sqrt{\Delta}\)</span>, which is short for the matrix with the square roots of the dissimilarities, is Euclidean as well. This follows because the square root is a Schoenberg transform (<span class="citation" data-cites="schoenberg_37">Schoenberg (<a href="references.html#ref-schoenberg_37" role="doc-biblioref">1937</a>)</span>, <span class="citation" data-cites="bavaud_11">Bavaud (<a href="references.html#ref-bavaud_11" role="doc-biblioref">2011</a>)</span>), and it implies that <span class="math inline">\(\tau(\Delta)=\tau(\sqrt{\Delta}\times\sqrt{\Delta})\)</span> is positive semi-definite. Thus the matrix @ref(eq:tau1) is positive semi-definite for all <span class="math inline">\(\alpha\geq 0\)</span>. By Danskin’s Theorem the one-sided directional derivative of <span class="math inline">\(\lambda_\star\)</span> at <span class="math inline">\(\alpha\)</span> is <span class="math inline">\(2x(\alpha)'\tau(\Delta)x(\alpha)+\alpha\)</span>, where <span class="math inline">\(x(\alpha)\)</span> is one of the minimizing eigenvectors. Because the one-sided derivative is non-negative, the function is non-decreasing (in fact increasing if <span class="math inline">\(\alpha&gt;0\)</span>).</p>
</div>
<p>Of course <span class="math inline">\(\lambda_\star(\alpha)=0\)</span> can still have negative solutions, and in particular it will have at least one negative solution if <span class="math inline">\(\lambda_\star(\alpha)\leq 0\)</span> for any <span class="math inline">\(\alpha\)</span>. There can even be negative solutions with <span class="math inline">\(\Delta+\alpha(E-I)\)</span> non-negative.</p>
</section>
<section id="solution" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="solution"><span class="header-section-number">8.2.2</span> Solution</h3>
<p>The solutions of <span class="math inline">\(\lambda_\star(\alpha)=0\)</span> can be computed and studied in more detail, using results first presented in the psychometric literature by <span class="citation" data-cites="cailliez_83">Cailliez (<a href="references.html#ref-cailliez_83" role="doc-biblioref">1983</a>)</span>. We reproduce his analysis here, with a somewhat different discussion that relies more on existing mathematical results.</p>
<p>In order to find the smallest <span class="math inline">\(\alpha\)</span> we solve the quadratic eigenvalue problem (<span class="citation" data-cites="tisseur_meerbergen_01">Tisseur and Meerbergen (<a href="references.html#ref-tisseur_meerbergen_01" role="doc-biblioref">2001</a>)</span>). WHY ??</p>
<p><span class="math display">\[\begin{equation}
\{\tau(\Delta\times\Delta)+2\alpha\tau(\Delta)+\frac12\alpha^2J\}y=0.
(\#eq:qep1)
\end{equation}\]</span></p>
<p>A solution <span class="math inline">\((y,\alpha)\)</span> of #ref(eq:qep1) is an eigen pair, in which <span class="math inline">\(y\)</span> is an eigenvector, and <span class="math inline">\(\alpha\)</span> the corresponding eigenvalue. The trivial solution <span class="math inline">\(y=e\)</span> satisfies #ref(eq:qep1) for any <span class="math inline">\(\alpha\)</span>. We are not really interested in the non-trivial eigenvectors here, but we will look at the relationship between the eigenvalues and the solutions of <span class="math inline">\(\lambda_\star(\alpha)=0\)</span>.</p>
<p>The eigenvalues can be complex, in which case they do not interest us. If <span class="math inline">\(\alpha\)</span> is a non-trivial real eigenvalue, then the rank of the Torgerson transform of the matrix in #ref(eq:qep1) is <span class="math inline">\(n-2\)</span>, but</p>
<p>To get rid of the annoying trivial solution <span class="math inline">\(y=e\)</span> we use a square orthonormal matrix whose first column is proportional to <span class="math inline">\(e\)</span>. Suppose <span class="math inline">\(L\)</span> contains the remaining <span class="math inline">\(n-1\)</span> columns. Now solve</p>
<p><span class="math display">\[\begin{equation}
\{L'\tau(\Delta\times\Delta)L+2\alpha L'\tau(\Delta)L+\frac12\alpha^2I\}y=0.
(\#eq:qep2)
\end{equation}\]</span></p>
<p>Note that the determinant of the polynomial matrix in @ref(eq:qep2) is a polynomial of degree <span class="math inline">\(2(n-1)\)</span> in <span class="math inline">\(\alpha\)</span>, which has <span class="math inline">\(2(n-1)\)</span> real or complex roots.</p>
<p>The next step is linearization (<span class="citation" data-cites="gohberg_lancaster_rodman_09">Gohberg, Lancaster, and Rodman (<a href="references.html#ref-gohberg_lancaster_rodman_09" role="doc-biblioref">2009</a>)</span>, chapter 1), which means finding a linear or generalized linear eigen problem with the same roots as @ref(eq:qep2). In our case this is the eigenvalue problem for the matrix</p>
<p><span class="math display">\[\begin{equation}
\begin{bmatrix}
\hfill 0&amp;\hfill I\\
-2L'\tau(\Delta\times\Delta)L&amp;-4L'\tau(\Delta)L
\end{bmatrix}
(\#eq:qep3)
\end{equation}\]</span></p>
</section>
<section id="examples" class="level3" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="examples"><span class="header-section-number">8.2.3</span> Examples</h3>
<section id="small-example" class="level4" data-number="8.2.3.1">
<h4 data-number="8.2.3.1" class="anchored" data-anchor-id="small-example"><span class="header-section-number">8.2.3.1</span> Small Example</h4>
<p>Here is a small artificial dissimilarity matrix.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  1  2  3  4 
1 +0 +1 +2 +5
2 +1 +0 +4 +2
3 +2 +4 +0 +1
4 +5 +2 +1 +0</code></pre>
</div>
</div>
<p>It is constructed such that <span class="math inline">\(\delta_{14}&gt;\delta_{12}+\delta_{24}\)</span> and that <span class="math inline">\(\delta_{23}&gt;\delta_{21}+\delta_{13}\)</span>. Because the triangle inequality is violated the dissimilarities are not distances in any metric space, and certainly not in a Euclidean one. Because the minimum dissimilarity is <span class="math inline">\(+1\)</span>, we require that the additive constant <span class="math inline">\(\alpha\)</span> is at least <span class="math inline">\(-1\)</span>.</p>
<p>The R function treq() in appendix @ref(apcodeclass) finds the smallest additive constant such that all triangle inequalities are satisfied. For this example it is <span class="math inline">\(\alpha=2\)</span>.</p>
<p>The Torgerson transform of <span class="math inline">\(\Delta\times\Delta\)</span> is</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  1      2      3      4     
1 +4.312 +2.688 +1.188 -8.188
2 +2.688 +2.062 -5.938 +1.188
3 +1.188 -5.938 +2.062 +2.688
4 -8.188 +1.188 +2.688 +4.312</code></pre>
</div>
</div>
<p>with eigenvalues</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] +12.954 +7.546  +0.000  -7.750 </code></pre>
</div>
</div>
<p>The smallest eigenvalue -7.75 is appropriately negative, and theorem @ref(thm:nmn2) shows that <span class="math inline">\(\Delta\times\Delta+7.75(E-I)\)</span> are squared distances between four points in the plane.</p>
<p>The upper bound for the smallest <span class="math inline">\(\alpha\)</span> from theorem @ref(thm:nmn1), computed by the R function acbound(), is 9.309475.</p>
<p>It is useful to look at a graphical representation of the minimum non-trivial eigenvalue of <span class="math inline">\(\tau((\Delta+\alpha(E-I))\times(\Delta+\alpha(E-I)))\)</span> as a function of <span class="math inline">\(\alpha\)</span>. The R function aceval() generates the data for the plot.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interval_files/figure-html/acplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see that the minimum non-trivial eigenvalue is a continuous function of <span class="math inline">\(\alpha\)</span>,but one which certainly is not convex or concave or differentiable. The graph crosses the horizontal axes near -8, -3, and +6.</p>
<p>To make this precise we apply the theory of section xxx. The R function acqep() finds the six non-trivial eigenvalues</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -8.192582+0.000000i  5.713075+0.000000i -3.500000+2.179449i
[4] -3.500000-2.179449i -2.807418+0.000000i -2.713075+0.000000i</code></pre>
</div>
</div>
<p>Two of the eigenvalues are complex conjugates, four are real. Of the real eigenvalues three are negative, and only one is positive, equal to +5.713. The table above gives the eigenvalues of the Torgerson transform, using all four real eigenvalues for <span class="math inline">\(\alpha\)</span>. The three negative ones do result in a positive semi-definite matrix with rank equal to <span class="math inline">\(n-2\)</span>, but they also create negative dissimilarities.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> -8.193  ******  +38.098 +13.885  +0.000  +0.000 
 +5.713  ******  +61.116 +43.441  +0.000  -0.000 
 -2.807  ******   +3.115  +0.402  +0.000  -0.000 
 -2.713  ******   +3.228  +0.215  +0.000  -0.000 </code></pre>
</div>
</div>
</section>
<section id="de-gruijter-example" class="level4" data-number="8.2.3.2">
<h4 data-number="8.2.3.2" class="anchored" data-anchor-id="de-gruijter-example"><span class="header-section-number">8.2.3.2</span> De Gruijter Example</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interval_files/figure-html/gruadd-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -20.527411+0.0000000i -10.174103+0.0000000i  -9.472504+0.0000000i
 [4]  -6.622263+0.3526193i  -6.622263-0.3526193i  -5.885691+0.2875441i
 [7]  -5.885691-0.2875441i  -5.640580+0.3668888i  -5.640580-0.3668888i
[10]  -4.391289+0.2532477i  -4.391289-0.2532477i  -3.708911+0.3868444i
[13]  -3.708911-0.3868444i  -3.238930+0.0000000i  -2.311379+0.0000000i
[16]  -1.369315+0.0000000i</code></pre>
</div>
</div>
</section>
<section id="ekman-example" class="level4" data-number="8.2.3.3">
<h4 data-number="8.2.3.3" class="anchored" data-anchor-id="ekman-example"><span class="header-section-number">8.2.3.3</span> Ekman Example</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interval_files/figure-html/ekkadd-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -5.713009655+0.00000000i -3.782729083+0.00000000i -1.791313475+0.00000000i
 [4] -1.628964140+0.00000000i -0.976213035+0.00000000i -0.744289350+0.04959388i
 [7] -0.744289350-0.04959388i -0.682321433+0.00000000i -0.534849034+0.00000000i
[10] -0.513033529+0.00000000i -0.497908376+0.02481447i -0.497908376-0.02481447i
[13] -0.372321687+0.13138923i -0.372321687-0.13138923i -0.388308013+0.00000000i
[16] -0.229813135+0.18259852i -0.229813135-0.18259852i -0.286712033+0.00000000i
[19] -0.212601059+0.11851989i -0.212601059-0.11851989i  0.206312577+0.00000000i
[22] -0.194299448+0.00000000i  0.132767430+0.00000000i -0.079646956+0.00000000i
[25] -0.024193535+0.00000000i -0.006762279+0.00000000i</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="interval_files/figure-html/ekk3add-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -7.974065161+0.00000000i -4.867929358+0.00000000i -1.224234244+0.00000000i
 [4] -0.982237601+0.00000000i  0.785644808+0.00000000i  0.648677529+0.00000000i
 [7] -0.554033177+0.00000000i -0.542600618+0.01297027i -0.542600618-0.01297027i
[10]  0.486418243+0.00000000i -0.111892110+0.39235860i -0.111892110-0.39235860i
[13]  0.382974612+0.00000000i  0.353089664+0.00000000i -0.351610318+0.00000000i
[16] -0.307360690+0.00000000i -0.126594060+0.26307892i -0.126594060-0.26307892i
[19] -0.073544792+0.26986305i -0.073544792-0.26986305i -0.233302697+0.00000000i
[22] -0.008137562+0.19480062i -0.008137562-0.19480062i -0.138025415+0.11750706i
[25] -0.138025415-0.11750706i  0.120502647+0.00000000i</code></pre>
</div>
</div>
</section>
</section>
<section id="variation" class="level3" data-number="8.2.4">
<h3 data-number="8.2.4" class="anchored" data-anchor-id="variation"><span class="header-section-number">8.2.4</span> A Variation</h3>
<p>Alternatively, we could define our approximation problem as finding <span class="math inline">\(X\in\mathbb{R}^{n\times p}\)</span> and <span class="math inline">\(\alpha\)</span> such that <span class="math inline">\(\sqrt{\delta_{ij}^2+\alpha}\approx d_{ij}(X)\)</span>, or, equivalently, <span class="math inline">\(\Delta\times\Delta+\alpha(E-I)\approx D(X)\times D(X)\)</span>.</p>
<div class="cell">
<pre class="theorem cell-code"><code>For any $X\in\mathbb{R}^{n\times p}$ with $p=n-2$ there is an $\alpha$
such that $\sqrt{\delta_{ij}^2+\alpha}= d_{ij}(X)$.</code></pre>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Now we have</p>
<p><span class="math display">\[\begin{equation}
\tau(\Delta\times\Delta+\alpha(E-I)))=
  \tau(\Delta\times\Delta)+\frac12\alpha J.
(\#eq:tau2)
\end{equation}\]</span></p>
<p>The eigenvalues of <span class="math inline">\(\tau(\Delta\times\Delta)+\frac12\alpha J\)</span> are zero and <span class="math inline">\(\lambda_s+\frac12\alpha\)</span>, where the <span class="math inline">\(\lambda_s\)</span> are the <span class="math inline">\(n-1\)</span> non-trivial eigenvalues of <span class="math inline">\(\tau(\Delta\times\Delta)\)</span>. If <span class="math inline">\(\underline{\lambda}\)</span> is smallest eigenvalue we choose <span class="math inline">\(\alpha=-2\underline{\lambda}\)</span>, and <span class="math inline">\(\tau(\Delta\times\Delta)+\frac12\alpha J\)</span> is positive semi-definite of rank <span class="math inline">\(r\leq n-2\)</span>.</p>
</div>
<p>Note that theorem @ref(thm:nmn2) implies that for any <span class="math inline">\(\Delta\)</span> there is a strictly increasing differentiable transformation to the space of Euclidean distance matrices in <span class="math inline">\(n-2\)</span> dimensions. This is a version of what is sometimes described as <em>Guttman’s n-2 theorem</em> (<span class="citation" data-cites="lingoes_71">Lingoes (<a href="references.html#ref-lingoes_71" role="doc-biblioref">1971</a>)</span>). The proof we have given is that from <span class="citation" data-cites="deleeuw_R_70b">De Leeuw (<a href="references.html#ref-deleeuw_R_70b" role="doc-biblioref">1970</a>)</span>, Appendix B.</p>
</section>
</section>
<section id="interval-smacof" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="interval-smacof"><span class="header-section-number">8.3</span> Interval smacof</h2>
<p>In this section we introduce a double-phase alternating least squares algorithm that fits better into the smacof framework than the single-phase method proposed by <span class="citation" data-cites="cooper_72">Cooper (<a href="references.html#ref-cooper_72" role="doc-biblioref">1972</a>)</span>. We also restrict our linear transformations to be to be increasing and non-negative on the positive real axes.</p>
<p>To avoid various kinds of trivialities, assume not all <span class="math inline">\(d_{ij}(X)\)</span> are zero.</p>
<p>In the optimal scaling phase we must minimize</p>
<p><span class="math display">\[\begin{equation}
\sigma(X,\alpha,\beta)=\mathop{\sum\sum}_{1\leq i&lt;j\leq  n}w_{ij}(\alpha\delta_{ij}+\beta-d_{ij}(X))^2
(\#eq:intloss)
\end{equation}\]</span></p>
<p>The constraints are <span class="math inline">\(\alpha\delta_{ij}+\beta\geq 0\)</span> and <span class="math inline">\(\alpha\delta_{ij}+\beta\geq\alpha\delta_{kl}+\beta\)</span> if <span class="math inline">\(\delta_{ij}\geq\delta_{kl}\)</span>. These define pointed convex cone in the space of disparities. We need to project <span class="math inline">\(D(X)\)</span> on that cone, in the metric defined by <span class="math inline">\(W\)</span>. But it is easy to see that and equivalent set of constraints in <span class="math inline">\(\mathbb{R}^2\)</span> is <span class="math inline">\(\alpha\geq 0\)</span> and <span class="math inline">\(\alpha\delta_\text{min}+\beta\geq 0\)</span>. Again these two constraints define a pointed cone in two-dimensional <span class="math inline">\((\alpha,\beta)\)</span> space, where proje ction is much easier to handle thanin the generally much larger disparity space. Of course the projection metric in <span class="math inline">\((\alpha,\beta)\)</span> is different from the one in disparity space.</p>
<p>In addition to the inequality constraints we have the normalization constraint <span class="math display">\[\begin{equation}
\mathop{\sum\sum}_{1\leq i&lt;j\leq  n}w_{ij}(\alpha\delta_{ij}+\beta)^2=1,
(\#eq:intnorm)
\end{equation}\]</span> but as we have seen in chapter @ref(nonmtrmds) we can initially ignore that constraint, project on the cone, and then normalize the projection.</p>
<p>In order to simplify the notation we collect the <span class="math inline">\(d_{ij}(X)\)</span> in a vector <span class="math inline">\(d\)</span>, the <span class="math inline">\(\delta_{ij}\)</span> in a vector <span class="math inline">\(\delta\)</span> and the <span class="math inline">\(w_{ij}\)</span> in a diagonal matrix <span class="math inline">\(W\)</span>.</p>
<p>Let’s first get the trivial case where all <span class="math inline">\(\delta_{ij}\)</span> are equal out of the way. In that case the linear regression is singular, and we simply choose all <span class="math inline">\(\alpha\delta+\beta\)</span> equal to the constant <span class="math inline">\(e'Wd\)</span>, for example by setting <span class="math inline">\(\alpha=0\)</span> and <span class="math inline">\(\beta=e'Wd\)</span>. Applying the normalization condition @ref(eq:intnorm) then sets <span class="math inline">\(\beta=1\)</span>. From now on we assume in this section that not all <span class="math inline">\(\delta_{ij}\)</span> are equal.</p>
<p>Projecting on the cone gives us four possibilities. We can have <span class="math inline">\(\alpha=0\)</span> or <span class="math inline">\(\alpha\delta_\text{min}+\beta=0\)</span>, or both, or neither. We first analyze the case in which the unconstrained minimum of @ref(eq:intloss) is in the cone, which will be the most common case, especially in later smacof iterations. Using the fact that <span class="math inline">\(\delta'W\delta=e'We=1\)</span> we find that <span class="math display">\[\begin{equation}
\begin{bmatrix}\tilde\alpha\\\tilde\beta\end{bmatrix}=
\frac{1}{1-(e'W\delta)^2}\begin{bmatrix}\delta'(W-We e'W)d\\e'(W-W\delta\delta'W)d\end{bmatrix}.
(\#eq:intunc)
\end{equation}\]</span> If <span class="math inline">\(\tilde\alpha\geq 0\)</span> and <span class="math inline">\(\tilde\beta\geq-\alpha\delta_\text{min}\)</span> we are done. If not, we know the projection is on the line <span class="math inline">\(\alpha=0\)</span> or on the line <span class="math inline">\(\tilde\beta=-\alpha\delta_\text{min}\)</span>, or on their intersection, which is the origin.</p>
<p>First suppose the projection is on <span class="math inline">\(\alpha=0\)</span>. We find the minimizing <span class="math inline">\(\beta\)</span> equal to <span class="math inline">\(\overline{\beta}:=e'Wd\)</span>, which strictly satisfies the second constraint because <span class="math inline">\(\overline\beta&gt;-\alpha\delta_\text{min}=0\)</span>, and thus <span class="math inline">\((0,e'Wd)\)</span> is on the boundary of the cone. This also show that the origin, which has <span class="math inline">\(\sigma(X,0,0)=d'Wd\)</span>, can never be the projection. The minimum at <span class="math inline">\((0,e'Wd)\)</span> is <span class="math display">\[\begin{equation}
\sigma(X,0,e'Wd)=d'Wd-(d'We)^2
(\#eq:intvertexloss1)
\end{equation}\]</span> Or, alternatively, we can assume that the projection is on the vertex <span class="math inline">\(\beta=-\alpha\delta_\text{min}\)</span>, in which case the minimizing <span class="math inline">\(\alpha\)</span> is <span class="math display">\[\begin{equation}
\overline{\alpha}:=\frac{(\delta-\delta_\text{min})'Wd}{(\delta-\delta_\text{min})'W(\delta-\delta_\text{min})},
(\#eq:intalpha)
\end{equation}\]</span> which is always positive, and thus <span class="math inline">\((\overline{\alpha},-\overline{\alpha}\delta_\text{min})\)</span> is on the boundary of the cone. The minimum is <span class="math display">\[\begin{equation}
\sigma(X,\overline{\alpha},-\overline{\alpha}\delta_\text{min})=d'Wd-\frac{((\delta-\delta_\text{min})'Wd)^2}{(\delta-\delta_\text{min})'W(\delta-\delta_\text{min})}
(\#eq:intvertexloss2)
\end{equation}\]</span> If the unconstrained solution is not in the cone, then we choose the projection as the solution corresponding with the smallest of @ref(eq:intvertexloss1) and (@ref(eq:intvertexloss2).</p>
<section id="example" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="example"><span class="header-section-number">8.3.1</span> Example</h3>
<p>We illustrate finding the optimal linear transformation with a small example. We choose some arbitrary <span class="math inline">\(w\)</span>, <span class="math inline">\(\delta\)</span>, and <span class="math inline">\(d\)</span> and normalize them in the usual way.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">5</span>),<span class="fu">rep</span>(<span class="dv">2</span>,<span class="dv">5</span>))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> w <span class="sc">/</span> <span class="fu">sum</span>(w)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>delta <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">sum</span>(w <span class="sc">*</span> delta <span class="sc">^</span> <span class="dv">2</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>delta <span class="ot">&lt;-</span> delta <span class="sc">/</span> <span class="fu">sqrt</span> (s)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">sum</span> (w <span class="sc">*</span> d <span class="sc">^</span> <span class="dv">2</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">sum</span> (w <span class="sc">*</span> d <span class="sc">*</span> delta)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">*</span> (t <span class="sc">/</span> s)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After normalization the <span class="math inline">\(\delta_{\text{min}}\)</span> is 0.1448414. The pink region in figure @ref(fig:intconex) is the cone formed by the intersection of the half-spaces <span class="math inline">\(\alpha\geq 0\)</span> and <span class="math inline">\(\alpha\delta_{\text{min}}+\beta\geq 0\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="interval_files/figure-html/intconex-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Cone Projection</figcaption>
</figure>
</div>
</div>
</div>
<p>The unconstrained minimum is attained at -0.2541855, 0.9484652, the red point in figure @ref(fig:intconex), with stress equal to 0.0939827. That is clearly outside the cone, so we now consider projection on the two one-dimensional boundary rays. The blue point is 0, 0.7152935, the projection on <span class="math inline">\(\alpha\geq 0\)</span>. It is fairly close to the unconstrained minimum, with stress 0.1042239. The green point 0.6782764, -0.0982425is the projection on <span class="math inline">\(\beta=-\alpha\delta_{\text{min}}\)</span>, which has stress 0.2684117. Thus the blue point 0, 0.7152935is the actual projection on the cone in <span class="math inline">\((\alpha,\beta)\)</span> space, and the best fitting line has slope zero (which, in smacof, would make all disparities equal for the next iteration).</p>
<p>This is illustrated in a different way (with Shepard plots) in figure @ref(fig:intlineex), where we see the red, blue, and green lines corresponding with the red, blue, and green points in figure @ref(fig:intconex). Note that the green line goes through the point <span class="math inline">\((\delta_{\text{min}},0)\)</span>. The horizontal blue line is the best fitting one under the constraints.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="interval_files/figure-html/intlineex-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Fitted Lines</figcaption>
</figure>
</div>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-bavaud_11" class="csl-entry" role="listitem">
Bavaud, F. 2011. <span>“<span class="nocase">On the Schoenberg Transformations in Data Analysis: Theory and Illustrations</span>.”</span> <em>Journal of Classification</em> 28: 297–314.
</div>
<div id="ref-berge_63" class="csl-entry" role="listitem">
Berge, C. 1963. <em>Topological Spaces</em>. Oliver &amp; Boyd.
</div>
<div id="ref-cailliez_83" class="csl-entry" role="listitem">
Cailliez, F. 1983. <span>“<span class="nocase">The Analytical Solution to the Additive Constant Problem</span>.”</span> <em>Psychometrika</em> 48 (2): 305–8.
</div>
<div id="ref-cooper_72" class="csl-entry" role="listitem">
Cooper, L. G. 1972. <span>“<span class="nocase">A New Solution to the Additive Constant Problem in Metric Multidimensional Scaling</span>.”</span> <em>Psychometrika</em> 37 (3): 311–22.
</div>
<div id="ref-deleeuw_R_70b" class="csl-entry" role="listitem">
De Leeuw, J. 1970. <span>“<span>The Euclidean Distance Model</span>.”</span> Research Note 002-70. Department of Data Theory FSW/RUL.
</div>
<div id="ref-gohberg_lancaster_rodman_09" class="csl-entry" role="listitem">
Gohberg, I., P. Lancaster, and L. Rodman. 2009. <em>Matrix Polynomials</em>. Classic in Applied Mathematics. SIAM.
</div>
<div id="ref-lingoes_71" class="csl-entry" role="listitem">
Lingoes, J. C. 1971. <span>“<span class="nocase">Some Boundary Conditions for a Monotone Analysis of Symmetric Matrices</span>.”</span> <em>Psychometrika</em> 36 (2): 195–203.
</div>
<div id="ref-messick_abelson_56" class="csl-entry" role="listitem">
Messick, S. J., and R. P. Abelson. 1956. <span>“<span class="nocase">The Additive Constant Problem in Multidimensional Scaling</span>.”</span> <em>Psychometrika</em> 21 (1–17).
</div>
<div id="ref-schoenberg_37" class="csl-entry" role="listitem">
Schoenberg, I. J. 1937. <span>“<span class="nocase">On Certain Metric Spaces Arising From Euclidean Spaces by a Change of Metric and Their Imbedding in Hilbert Space</span>.”</span> <em>Annals of Mathematics</em> 38 (4): 787–93.
</div>
<div id="ref-taussky_49" class="csl-entry" role="listitem">
Taussky, O. 1949. <span>“<span class="nocase">A Recurring Theorem on Determinants</span>.”</span> <em>American Mathematical Monthly</em> 56: 672–76.
</div>
<div id="ref-tisseur_meerbergen_01" class="csl-entry" role="listitem">
Tisseur, F., and K. Meerbergen. 2001. <span>“<span>The Quadratic Eigenvalue Problem</span>.”</span> <em><span>SIAM</span> Review</em> 43 (2): 235–86.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./nonmetric.html" class="pagination-link" aria-label="Nonmetric MDS">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Nonmetric MDS</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./polynomial.html" class="pagination-link" aria-label="Polynomial MDS">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Polynomial MDS</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>